#!/usr/bin/env bash

set -euo pipefail

echo "=== Paperless Receipts installer ==="

# Check for docker-compose
if ! command -v docker >/dev/null 2>&1; then
  echo "Error: docker not found in PATH. Please install Docker and try again."
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Error: 'docker compose' plugin is not available. Please install docker-compose-plugin and try again."
  exit 1
fi

# Get directories from user
read -rp "Base install directory [\$HOME/paperless-app]: " APP_DIR
APP_DIR="${APP_DIR:-$HOME/paperless-app}"

read -rp "Data storage directory [\$HOME/paperless-data]: " DATA_DIR
DATA_DIR="${DATA_DIR:-$HOME/paperless-data}"

read -rp "Consume directory [\$HOME/paperless-consume]: " CONSUME_DIR
CONSUME_DIR="${CONSUME_DIR:-$HOME/paperless-consume}"

echo
echo
echo "Install dir:  $APP_DIR"
echo "Data dir:     $DATA_DIR"
echo "Consume dir:  $CONSUME_DIR"
read -rp "Proceed with these paths? [y/N] " CONFIRM
[[ "$CONFIRM" == "y" || "$CONFIRM" == "Y" ]] || { echo "Aborting."; exit 1; }


# Set Timezone:

if command -v timedatectl >/dev/null 2>&1; then
  SYS_TZ="$(timedatectl show -p Timezone --value 2>/dev/null || echo "")"
  TZ_CHOICE="${SYS_TZ}"

  echo "Detected timezone: $TZ_CHOICE"
  read -rp "Use this timezone? [Y/n]: " ANS
  if [ "$ANS" = "n" ] || [ "$ANS" = "N" ]; then
    read -rp "Enter timezone (e.g. America/New_York) [UTC]: " MANUAL_TZ
    TZ_CHOICE="$MANUAL_TZ"
  fi

  if ! timedatectl list-timezones | grep -F "$TZ_CHOICE"; then
    echo "Warning: '$TZ_CHOICE' is not a known timezone. Please try again."
    exit 1
  fi

else
  echo "Error: timedatectl not found; can't validate time zone. Please install systemd/timedatectl or set PAPERLESS_TIME_ZONE manually in docker-compose.env."
  read -rp "Exit or set timezone to 'UTC'? [Y: exit / n: set UTC]" ANS
  if [ "$ANS" = "n" ] || [ "$ANS" = "N" ]; then
    TZ_CHOICE="UTC"
  else
    exit 1
  fi
fi


# get user name and password:

read -rp "Set username [admin]: " USERNAME
USERNAME="${USERNAME:-admin}"

read -rp "Set email for user (for password recovery) [admin@example.com]: " USER_EMAIL
USER_EMAIL="${USER_EMAIL:-admin@example.com}"

PASSWORD=""
PASSWORD_REPEAT=""

while true; do
  read -r -sp "Paperless password: " PASSWORD
  echo ""

  if [[ -z $PASSWORD ]] ; then
    echo "Password cannot be empty."
    continue
  fi

  read -r -sp "Paperless password (again): " PASSWORD_REPEAT
  echo ""

  if [[ ! "$PASSWORD" == "$PASSWORD_REPEAT" ]] ; then
    echo "Passwords did not match"
  else
    break
  fi
done

# Done collecting install info from user
# Now make directories

mkdir -p "$APP_DIR"/{Scripts,helper}
mkdir -p "$DATA_DIR"/{Database,Data,Media,cache,export,logs}
mkdir -p "$CONSUME_DIR"

MODEL_DIR="$APP_DIR/helper/models"
mkdir -p "$MODEL_DIR"

for d in "$APP_DIR" "$DATA_DIR" "$CONSUME_DIR"; do
  if [ ! -w "$d" ]; then
    echo "Error: directory '$d' is not writable by $(whoami)."
    exit 1
  fi
done


TRAY_BIN="${APP_DIR}/paperless_receipts.bin"
POST_CONSUME="${APP_DIR}/Scripts/post_consume.py"

# Download files from repo
DOWNLOAD_FILES=(
"docker-compose.yml"
"paperless_receipts.bin"
"helper/app.py"
"helper/prep_ocr.py"
"helper/Dockerfile"
"paperless_on.png"
"paperless_off.png"
"paperless_config.template.json"
"Scripts/post_consume.py"
)

for r_path in "${DOWNLOAD_FILES[@]}"; do
  url="https://raw.githubusercontent.com/jazzathoth/paperless-receipts/main/${r_path}"
  dest="${APP_DIR}/${r_path}"

  if [ ! -f "$dest" ]; then
    echo "Downloading $r_path..."
    mkdir -p "$(dirname "$dest")"
    curl -fsSL "$url" -o "$dest"
  else
    echo "$r_path already exists in $APP_DIR, no download needed."
  fi
done

if [ -f "$TRAY_BIN" ]; then
  chmod +x "$TRAY_BIN" || echo "Warning: could not make $TRAY_BIN executable"
fi

if [ -f "$POST_CONSUME" ]; then
  chmod +x "$POST_CONSUME" || echo "Warning: could not make $POST_CONSUME executable"
fi


# Generate .env file
ENV_FILE="$APP_DIR/.env"
LLM_MODEL_PATH="$MODEL_DIR/paperless-helper.gguf"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh
PAPERLESS_DATA_DIR="$DATA_DIR"
CONSUME_DIR="$CONSUME_DIR"

# Helper-specific
LLM_MODEL_PATH="$LLM_MODEL_PATH"
EOF

# Generate docker-compose.env
DC_ENV_FILE="$APP_DIR/docker-compose.env"
PAPERLESS_URL="http://127.0.0.1:8000"

if [ -f "$DC_ENV_FILE" ]; then
  echo "docker-compose.env already exists, leaving it as-is."
else
  echo "Creating docker-compose.env..."


  SECRET="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64 || true)"

  if [ -z "$SECRET" ]; then
    echo "Failed to generate random secret key."
    exit 1
  fi

  cat >"$DC_ENV_FILE" <<EOF
PAPERLESS_URL=$PAPERLESS_URL
PAPERLESS_TIME_ZONE=$TZ_CHOICE
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_SECRET_KEY=$SECRET
EOF

  echo "Wrote new docker-compose.env with generated PAPERLESS_SECRET_KEY."
fi


# Write launcher .desktop file

DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/paperless-receipts.desktop"

mkdir -p "$DESKTOP_DIR"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Paperless Receipts
Comment=Paperless-ngx with LLM for data extraction
Exec=${APP_DIR}/paperless_receipts.bin
Path=${APP_DIR}
Icon=${APP_DIR}/paperless_on.png
Terminal=false
Categories=Office;
EOF

chmod +x "$DESKTOP_FILE"

echo "Created launcher: $DESKTOP_FILE"


echo
echo "Wrote .env to: $ENV_FILE"
echo "Wrote docker-compose.env to $DC_ENV_FILE"
echo "Data subdirs created under: $DATA_DIR"
echo
echo "Place your GGUF model at:"
echo "  $LLM_MODEL_PATH"
echo "…or edit LLM_MODEL_PATH in .env if you use a different location."
echo

# 7) (Optional) Pre-pull images so first start is faster
echo "Pulling Docker images (this may take a while)..."
( cd "$APP_DIR" && docker compose pull ) || echo "Warning: docker compose pull failed; you'll see errors on first start if images are missing."

cd "$APP_DIR" && docker compose up --detach db
sleep 15
cd "$APP_DIR" && docker compose stop

cd "$APP_DIR" && docker compose run --rm \
  -e DJANGO_SUPERUSER_PASSWORD="$PASSWORD" \
  webserver \
  createsuperuser --noinput --username "$USERNAME" --email "$USER_EMAIL"

echo "Starting the containers:"
cd "$APP_DIR" && docker compose up --detach
sleep 15

echo "Setting up the db for receipts"

CONFIG_JSON="$APP_DIR/paperless_config.template.json"

while IFS= read -r doc_type; do
  curl -sS -u "$USERNAME:$PASSWORD" \
    -H "Content-Type: application/json" \
    -d "$doc_type" \
    "$PAPERLESS_URL/api/document_types/" \
    >/dev/null
    done < <(jq -c '.document_types[] | del(.id)' "$CONFIG_JSON")

while IFS= read -r tag; do
  curl -sS -u "$USERNAME:$PASSWORD" \
       -H "Content-Type: application/json" \
       -d "$tag" \
       "$PAPERLESS_URL/api/tags/" \
       >/dev/null
       done < <(jq -c '.tags[] | del(.id)' "$CONFIG_JSON")

while IFS= read -r field; do
  curl -sS -u "$USERNAME:$PASSWORD" \
       -H "Content-Type: application/json" \
       -d "$field" \
       "$PAPERLESS_URL/api/custom_fields/" \
       >/dev/null
       done < <(jq -c '.custom_fields[] | del(.id)' "$CONFIG_JSON")

FINISHED_CF_NAME="Finished"  # or whatever the name actually is in Paperless

CF_JSON="$(
  curl -sS -u "$USERNAME:$PASSWORD" \
       "$PAPERLESS_URL/api/custom_fields/?page_size=1000"
)"


FINISHED_CF_ID="$(
  echo "$CF_JSON" \
  | jq -r --arg name "$FINISHED_CF_NAME" \
      '.results[] | select(.name == $name) | .id'
)"


if [ -z "$FINISHED_CF_ID" ] || [ "$FINISHED_CF_ID" = "null" ]; then
  echo "ERROR: Could not find custom field named '$FINISHED_CF_NAME'."
  echo "       Check that your template's custom_fields[] names match and try again."
  exit 1
fi

echo "Using finished custom field id: $FINISHED_CF_ID"

CF_ID_LIST="$(
  echo "$CF_JSON" \
  | jq '[.results[].id]'
)"

while IFS= read -r wf; do
  echo "Posting workflow payload:"
  echo "$wf"
  echo

  curl -v \
       -u "$USERNAME:$PASSWORD" \
       -H "Content-Type: application/json" \
       -d "$wf" \
       "$PAPERLESS_URL/api/workflows/"

  echo    # newline
  echo "-------------------------------------------"
  sleep 1
done < <(
  jq -c \
    --argjson finished_id "$FINISHED_CF_ID" \
    --argjson cf_ids "$CF_ID_LIST" \
    '
    .workflows[]
    # strip top-level id if present
    | del(.id)
    # drop ids inside actions & triggers & webhook if they exist
    | .actions  |= (map(del(.id) | if .webhook? then .webhook |= del(.id) else . end
      | .assign_custom_fields = $cf_ids
      | .assign_custom_fields_values =
        (reduce $cf_ids[] as $id ({}; . + {
          ($id|tostring):
            (if $id == $finished_id then false else null end)
        }))

    ))
    | .triggers |= (map(del(.id)))
    # rewrite filter_custom_field_query only where it is non-null
    | .triggers |= (map(
        if .filter_custom_field_query != null then
          .filter_custom_field_query =
            ("[\"AND\",[[" + ($finished_id|tostring) + ",\"exact\",\"true\"]]]")
        else
          .
        end
      ))
  ' "$CONFIG_JSON"
)


sleep 15

cd "$APP_DIR" && docker compose down

echo
echo "Install complete."
echo "To start the stack manually:  cd \"$APP_DIR\" && docker compose up -d"
echo "Once your tray app is built and copied into $APP_DIR, you can run it from there to control start/stop."
